apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: happyhour-node-cli
  annotations:
    github.com/project-slug: healthline/happyhour-node-cli
spec:
  type: cli
  lifecycle: experimental
  owner: team-platejoy
